name: deploy gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set Creds
      run: git config user.name "CryptoGrampy" && git config user.email "CryptoGrampy@protonmail.com"
    - name: Build
      run: |
        npm i
        npm run deploy
